import { ROLEIDS } from '~/common/const/permission';

export const mockCVs = [
  {
    user_id: ROLEIDS.Client,
    name: 'Abdullah Khilal Maryam',
    email: 'abdullah@gmail.com',
    address: 'Indonesia',
    linkedin: 'https://linkedin.com/in/abdullah',
    about: 'Software engineer with passion in backend and AI.',

    interest: ['AI', 'Backend', 'Cloud'] as string[],
    skill: ['Node.js', 'TypeScript', 'PostgreSQL'] as string[],

    education: [
      {
        name: 'Universitas Indonesia',
        major: 'Informatika',
      },
    ],
    experience: [
      {
        role: 'Backend Engineer',
        company: 'AnalyticaCV',
        description: 'Develop API and multi-tenant system',
        start: '2024-01',
        end: '2024-12',
      },
    ],
    projects: [
      {
        title: 'AnalyticaCV',
        description: 'AI-powered CV analyzer',
      },
    ],
    certificate: [
      {
        title: 'AWS Cloud Practitioner',
        issuer: 'Amazon',
        year: 2023,
        url: 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Karlina Putri',
    email: 'karlina@gmail.com',
    address: 'Surabaya, Jawa Timur',
    linkedin: 'https://linkedin.com/in/karlina',
    about: 'Quality Assurance with focus on automation testing',
    interest: ['AI', 'Automation', 'Pentest'] as string[],
    skill: ['Node.js', 'TypeScript', 'Playwright', 'Cypress', 'Selenium'] as string[],
    education: [{ name: 'Universitas Gadjah Mada', major: 'Sistem Informasi' }],
    experience: [
      {
        role: 'Quality Assurance Engineer',
        company: 'PT. Telkom Indonesia',
        description: 'Tester for multi-tenant system & automation framework development',
        start: '2024-01',
        end: '2024-12',
      },
    ],
    projects: [
      { title: 'SaaS E-Commerce Multi-Tenant', description: 'Building scalable e-commerce platform with tenant isolation' },
    ],
    certificate: [
      {
        title: 'AWS Certified Practitioner - QA',
        issuer: 'Amazon Web Services',
        year: 2024,
        url: 'https://aws.amazon.com/certification/certified-qa-practitioner/',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@outlook.com',
    address: 'Bandung, Jawa Barat',
    linkedin: 'https://linkedin.com/in/ahmadfauzi',
    about: 'UI/UX Designer passionate about human-centered design',
    interest: ['Design System', 'Figma', 'Accessibility'] as string[],
    skill: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research'] as string[],
    education: [{ name: 'Institut Teknologi Bandung', major: 'Desain Produk' }],
    experience: [
      {
        role: 'Senior UI/UX Designer',
        company: 'GoJek',
        description: 'Redesign GoPay & GoFood experience',
        start: '2022-06',
        end: '2022-06',
      },
    ],
    projects: [{ title: 'GoPay Redesign 2024', description: 'Increased transaction completion rate by 32%' }],
    certificate: [
      {
        title: 'Google UX Design Professional Certificate',
        issuer: 'Coursera',
        year: 2023,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'dr. Nadia Sari',
    email: 'nadia.sari@rsup.co.id',
    address: 'Jakarta Selatan, DKI Jakarta',
    linkedin: 'https://linkedin.com/in/drnadiasari',
    about: 'Dokter Spesialis Anak dengan minat riset vaksin',
    interest: ['Pediatri', 'Vaksinologi', 'Kesehatan Anak'] as string[],
    skill: ['Diagnosis Klinis', 'Konseling Orang Tua', 'Riset Klinis'] as string[],
    education: [
      { name: 'Universitas Indonesia', major: 'Kedokteran' },
      { name: 'Universitas Indonesia', major: 'Spesialis Anak' },
    ],
    experience: [
      {
        role: 'Dokter Spesialis Anak',
        company: 'RSUPN Dr. Cipto Mangunkusumo',
        description: 'Menangani kasus anak dengan penyakit infeksi berat',
        start: '2020-03',
        end: '2020-03',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Fellowship Vaksinologi',
        issuer: 'IDAI',
        year: 2024,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Rizky Pratama',
    email: 'rizky.pratama@yahoo.com',
    address: 'Yogyakarta',
    linkedin: 'https://linkedin.com/in/rizkypratama',
    about: 'Full-stack Developer | Laravel & React Enthusiast',
    interest: ['Web Performance', 'Microservices', 'DevOps'] as string[],
    skill: ['Laravel', 'React', 'MySQL', 'Docker', 'AWS'] as string[],
    education: [{ name: 'Universitas Gadjah Mada', major: 'Teknik Informatika' }],
    experience: [
      {
        role: 'Backend Developer',
        company: 'Tokopedia',
        description: 'Maintain payment gateway integration',
        start: '2023-01',
        end: '2023-01',
      },
    ],
    projects: [{ title: 'Marketplace Internal Tool', description: 'Internal dashboard for merchant management' }],
    certificate: [
      {
        title: 'AWS Certified Solutions Architect – Associate',
        issuer: 'Amazon',
        year: 2024,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Siti Aisyah',
    email: 'siti.aisyah@bankmandiri.co.id',
    address: 'Tangerang, Banten',
    linkedin: 'https://linkedin.com/in/siti-aisyah',
    about: 'Digital Marketing Specialist di sektor perbankan',
    interest: ['Growth Marketing', 'SEO', 'Content Strategy'] as string[],
    skill: ['Google Analytics', 'Meta Ads', 'SEO', 'Copywriting'] as string[],
    education: [{ name: 'Universitas Padjadjaran', major: 'Ilmu Komunikasi' }],
    experience: [
      {
        role: 'Digital Marketing Manager',
        company: 'Bank Mandiri',
        description: 'Meningkatkan akuisisi nasabah digital hingga 45%',
        start: '2021-08',
        end: '2021-08',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Google Digital Marketing & E-commerce',
        issuer: 'Google',
        year: 2023,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Budi Santoso',
    email: 'budi.santoso@pln.co.id',
    address: 'Semarang, Jawa Tengah',
    linkedin: 'https://linkedin.com/in/budisantoso-eng',
    about: 'Electrical Engineer | Smart Grid & Renewable Energy',
    interest: ['Smart Grid', 'Solar PV', 'Energy Management'] as string[],
    skill: ['ETAP', 'AutoCAD', 'PLC Programming', 'SCADA'] as string[],
    education: [{ name: 'Institut Teknologi Sepuluh Nopember', major: 'Teknik Elektro' }],
    experience: [
      {
        role: 'Project Engineer',
        company: 'PLN (Persero)',
        description: 'Pembangunan gardu induk 150 kV',
        start: '2019-04',
        end: '2019-04',
      },
    ],
    projects: [{ title: 'PLTS Atap 500 kWp', description: 'Rooftop solar project untuk kantor pusat PLN Jateng' }],
    certificate: [],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Laras Widya',
    email: 'laras.widya@gmail.com',
    address: 'Malang, Jawa Timur',
    linkedin: 'https://linkedin.com/in/laraswidya',
    about: 'Content Creator & Travel Photographer',
    interest: ['Travel', 'Fotografi', 'Videografi'] as string[],
    skill: ['Adobe Premiere', 'Lightroom', 'Drone Pilot', 'Storytelling'] as string[],
    education: [{ name: 'Universitas Brawijaya', major: 'Ilmu Komunikasi' }],
    experience: [
      {
        role: 'Freelance Content Creator',
        company: 'Self-employed',
        description: 'Bekerja sama dengan brand pariwisata & lifestyle',
        start: '2021-01',
        end: '2021-01',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'DJI Mavic Pilot License',
        issuer: 'DJI',
        year: 2023,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Muhammad Ilham',
    email: 'ilham.data@bumi.co.id',
    address: 'Balikpapan, Kalimantan Timur',
    linkedin: 'https://linkedin.com/in/muhammadilham',
    about: 'Data Analyst di industri migas',
    interest: ['Data Visualization', 'Python', 'Predictive Maintenance'] as string[],
    skill: ['Python', 'Power BI', 'SQL', 'Tableau'] as string[],
    education: [{ name: 'Institut Teknologi Bandung', major: 'Teknik Perminyakan' }],
    experience: [
      {
        role: 'Data Analyst',
        company: 'Pertamina Hulu Energi',
        description: 'Production optimization using data analytics',
        start: '2022-07',
        end: '2022-07',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Microsoft Certified: Power BI Data Analyst Associate',
        issuer: 'Microsoft',
        year: 2024,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Citra Dewi',
    email: 'citra.dewi@hotel.co.id',
    address: 'Bali',
    linkedin: 'https://linkedin.com/in/citradewi',
    about: 'Hotel General Manager dengan pengalaman 12 tahun di hospitality',
    interest: ['Revenue Management', 'Guest Experience', 'Sustainable Tourism'] as string[],
    skill: ['Revenue Strategy', 'Team Leadership', 'P&L Management'] as string[],
    education: [{ name: 'STP Trisakti', major: 'Manajemen Perhotelan' }],
    experience: [
      {
        role: 'General Manager',
        company: 'The Legian, a Luxury Collection Hotel',
        description: '5-star luxury resort di Seminyak',
        start: '2023-03',
        end: '2023-03',
      },
    ],
    projects: [],
    certificate: [],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Fajar Nugroho',
    email: 'fajar.nugroho@shopee.co.id',
    address: 'Jakarta Barat',
    linkedin: 'https://linkedin.com/in/fajarnugroho',
    about: 'Mobile Developer Android | Kotlin Lover',
    interest: ['Android', 'Jetpack Compose', 'Performance'] as string[],
    skill: ['Kotlin', 'Jetpack Compose', 'Firebase', 'CI/CD'] as string[],
    education: [{ name: 'Universitas Bina Nusantara', major: 'Ilmu Komputer' }],
    experience: [
      {
        role: 'Senior Android Engineer',
        company: 'Shopee Indonesia',
        description: 'Developing Shopee Express & logistics feature',
        start: '2021-11',
        end: '2021-11',
      },
    ],
    projects: [],
    certificate: [],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Putri Anggraini',
    email: 'putri.anggraini@lawfirm.id',
    address: 'Jakarta Pusat',
    linkedin: 'https://linkedin.com/in/putrianggraini',
    about: 'Pengacara spesialis hukum korporasi dan merger',
    interest: ['Corporate Law', 'M&A', 'Contract Drafting'] as string[],
    skill: ['Legal Research', 'Negosiasi', 'Due Diligence'] as string[],
    education: [{ name: 'Universitas Indonesia', major: 'Ilmu Hukum' }],
    experience: [
      {
        role: 'Senior Associate Lawyer',
        company: 'Hadiputranto, Hadinoto & Partners',
        description: 'Menangani transaksi M&A senilai > Rp 5T',
        start: '2020-02',
        end: '2020-02',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Advokat PERADI',
        issuer: 'Peradi',
        year: 2019,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Dian Kusuma',
    email: 'dian.kusuma@school.id',
    address: 'Surabaya, Jawa Timur',
    linkedin: 'https://linkedin.com/in/diankusuma',
    about: 'Guru Matematika SMP dengan metode pembelajaran kreatif',
    interest: ['STEM Education', 'Gamification', 'Inklusi'] as string[],
    skill: ['Lesson Planning', 'Google Classroom', 'Assessment Design'] as string[],
    education: [{ name: 'Universitas Negeri Surabaya', major: 'Pendidikan Matematika' }],
    experience: [
      {
        role: 'Guru Matematika',
        company: 'SMP Negeri 1 Surabaya',
        description: 'Mengajar kelas 7-9, koordinator olimpiade',
        start: '2018-08',
        end: '2018-08',
      },
    ],
    projects: [{ title: 'Math Game App', description: 'Aplikasi game matematika untuk siswa SMP' }],
    certificate: [
      {
        title: 'Sertifikasi Guru Profesional',
        issuer: 'Kemdikbud',
        year: 2022,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Chef Arief Wicaksono',
    email: 'arief@restaurant.co.id',
    address: 'Bandung, Jawa Barat',
    linkedin: 'https://linkedin.com/in/chef-arief',
    about: 'Executive Chef spesialisasi fusion Indonesian-Western',
    interest: ['Molecular Gastronomy', 'Local Ingredients', 'Menu Engineering'] as string[],
    skill: ['Knife Skills', 'Menu Development', 'Food Costing'] as string[],
    education: [{ name: 'Akademi Kuliner Indonesia', major: 'Culinary Arts' }],
    experience: [
      {
        role: 'Executive Chef',
        company: 'The Valley Restaurant',
        description: 'Mengelola kitchen 5-star hotel',
        start: '2022-05',
        end: '2022-05',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Certified Executive Chef',
        issuer: 'American Culinary Federation',
        year: 2023,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Rina Setiawati',
    email: 'rina.setiawati@architect.id',
    address: 'Jakarta Selatan',
    linkedin: 'https://linkedin.com/in/rinasetiawati',
    about: 'Arsitek berkelanjutan dengan fokus green building',
    interest: ['Sustainable Design', 'BIM', 'Tropical Architecture'] as string[],
    skill: ['Revit', 'SketchUp', 'Lumion', 'Green Building Certification'] as string[],
    education: [{ name: 'Universitas Trisakti', major: 'Arsitektur' }],
    experience: [
      {
        role: 'Lead Architect',
        company: 'PT. Atelier Riri',
        description: 'Desain resort ramah lingkungan di Bali',
        start: '2021-03',
        end: '2021-03',
      },
    ],
    projects: [{ title: 'Eco Resort Nusa Penida', description: 'Resort berkapasitas 50 kamar dengan sertifikasi Greenship' }],
    certificate: [
      {
        title: 'Greenship Professional',
        issuer: 'Green Building Council Indonesia',
        year: 2022,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Bayu Pratama',
    email: 'bayu@startup.id',
    address: 'Jakarta',
    linkedin: 'https://linkedin.com/in/bayupratama',
    about: 'Product Manager di fintech startup',
    interest: ['Product Strategy', 'User Growth', 'A/B Testing'] as string[],
    skill: ['Jira', 'Figma', 'SQL', 'Roadmapping'] as string[],
    education: [{ name: 'Universitas Bina Nusantara', major: 'Manajemen' }],
    experience: [
      {
        role: 'Senior Product Manager',
        company: 'OVO',
        description: 'Lead fitur OVO Invest',
        start: '2022-09',
        end: '2022-09',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Certified Scrum Product Owner',
        issuer: 'Scrum Alliance',
        year: 2023,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Intan Permata',
    email: 'intan.permata@hr.co.id',
    address: 'Bekasi, Jawa Barat',
    linkedin: 'https://linkedin.com/in/intanpermata',
    about: 'HR Business Partner dengan pengalaman talent acquisition',
    interest: ['People Analytics', 'Employee Engagement', 'Diversity'] as string[],
    skill: ['Recruitment', 'Performance Management', 'Workday'] as string[],
    education: [{ name: 'Universitas Indonesia', major: 'Psikologi' }],
    experience: [
      {
        role: 'HR Business Partner',
        company: 'Unilever Indonesia',
        description: 'Partner untuk divisi sales & marketing',
        start: '2020-06',
        end: '2020-06',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'SHRM Certified Professional',
        issuer: 'SHRM',
        year: 2024,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Agung Wijaya',
    email: 'agung.wijaya@logistik.id',
    address: 'Surabaya, Jawa Timur',
    linkedin: 'https://linkedin.com/in/agungwijaya',
    about: 'Supply Chain Manager di e-commerce',
    interest: ['Warehouse Optimization', 'Last Mile', 'Inventory Management'] as string[],
    skill: ['SAP', 'WMS', 'Forecasting', 'Lean Six Sigma'] as string[],
    education: [{ name: 'Institut Teknologi Sepuluh Nopember', major: 'Teknik Industri' }],
    experience: [
      {
        role: 'Supply Chain Manager',
        company: 'Lazada Indonesia',
        description: 'Mengelola 12 warehouse di Indonesia',
        start: '2021-04',
        end: '2021-04',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Certified Supply Chain Professional',
        issuer: 'APICS',
        year: 2023,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Lina Marlina',
    email: 'lina.marlina@farmasi.id',
    address: 'Bogor, Jawa Barat',
    linkedin: 'https://linkedin.com/in/linamarlina',
    about: 'Apoteker klinis di rumah sakit',
    interest: ['Farmakoterapi', 'Patient Counseling', 'Antibiotik Stewardship'] as string[],
    skill: ['Drug Information', 'Medication Review', 'Klinik Farmasi'] as string[],
    education: [{ name: 'Universitas Padjadjaran', major: 'Farmasi' }],
    experience: [
      {
        role: 'Apoteker Klinis',
        company: 'RS Siloam Bogor',
        description: 'Memberikan konsultasi obat pasien rawat inap',
        start: '2022-01',
        end: '2022-01',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Apoteker Kompeten',
        issuer: 'IAI',
        year: 2021,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Hendra Saputra',
    email: 'hendra@finance.co.id',
    address: 'Medan, Sumatera Utara',
    linkedin: 'https://linkedin.com/in/hendrasaputra',
    about: 'Financial Analyst di bank daerah',
    interest: ['Credit Risk', 'Financial Modeling', 'Portfolio Management'] as string[],
    skill: ['Excel Advanced', 'Bloomberg', 'SQL', 'Valuation'] as string[],
    education: [{ name: 'Universitas Sumatera Utara', major: 'Akuntansi' }],
    experience: [
      {
        role: 'Senior Financial Analyst',
        company: 'Bank Sumut',
        description: 'Analisis kredit korporasi',
        start: '2020-07',
        end: '2020-07',
      },
    ],
    projects: [],
    certificate: [
      {
        title: 'Chartered Financial Analyst Level I',
        issuer: 'CFA Institute',
        year: 2024,
        url: '#',
      },
    ],
  },
  {
    user_id: ROLEIDS.Client,
    name: 'Wulan Sari',
    email: 'wulan.sari@ngo.org',
    address: 'Yogyakarta',
    linkedin: 'https://linkedin.com/in/wulansari',
    about: 'Social Worker & Program Coordinator di LSM pendidikan anak',
    interest: ['Community Development', 'Child Protection', 'Fundraising'] as string[],
    skill: ['Program Design', 'Monitoring Evaluation', 'Grant Writing'] as string[],
    education: [{ name: 'Universitas Gadjah Mada', major: 'Ilmu Kesejahteraan Sosial' }],
    experience: [
      {
        role: 'Program Coordinator',
        company: 'Yayasan Sayangi Anak',
        description: 'Mengelola program pendidikan di 15 desa',
        start: '2021-02',
        end: '2021-02',
      },
    ],
    projects: [{ title: 'Sekolah Lapang Anak', description: 'Program pendidikan non-formal untuk anak putus sekolah' }],
    certificate: [],
  },
];
