// Auto-generated file - do not edit manually
// Generated at: 2025-12-13T18:07:05.487Z

// Hierarchical permissions (includes parent route permissions)
export const routePermissions: Record<string, string[]> = {
  '/pricing': [],
  '/order': [],
  '/charts': [],
  '/backoffice': ['client:read'],
  '/[clientId]': ['customer:read_profile'],
  '/backoffice/clients': ['client:read'],
  '/auth/reset-password': [],
  '/auth/register': [],
  '/auth/login': [],
  '/auth/forgot-password': [],
  '/[clientId]/customer': ['customer:read_profile'],
  '/[clientId]/admin': ['customer:read_profile', 'customer:read'],
  '/backoffice/clients/create': ['client:read'],
  '/backoffice/clients/[clientId]': ['client:read'],
  '/[clientId]/auth/register': ['customer:read_profile'],
  '/[clientId]/auth/login': ['customer:read_profile'],
  '/[clientId]/customer/orders': ['customer:read_profile', 'customer:read'],
  '/[clientId]/admin/customers': ['customer:read_profile', 'customer:read', 'customer:delete'],
  '/backoffice/clients/[clientId]/customers': ['client:read', 'customer:read', 'customer:delete'],
  '/[clientId]/customer/orders/[orderId]': ['customer:read_profile', 'customer:read'],
  '/[clientId]/customer/me/profile': ['customer:read_profile'],
  '/[clientId]/admin/customers/create': ['customer:read_profile', 'customer:read', 'customer:delete'],
  '/[clientId]/admin/customers/[customerId]': ['customer:read_profile', 'customer:read', 'customer:delete'],
  '/backoffice/clients/[clientId]/customers/[customerId]': ['client:read', 'customer:read', 'customer:delete', 'customer:update'],
  '/[clientId]/customer/me/profile/update': ['customer:read_profile'],
  '/[clientId]/admin/customers/[customerId]/update': ['customer:read_profile', 'customer:read', 'customer:delete', 'customer:update'],
  '/:clientId': ['customer:read_profile'],
  '/auth': [],
  '/:clientId/customer': ['customer:read_profile'],
  '/:clientId/admin': ['customer:read_profile', 'customer:read'],
  '/backoffice/clients/:clientId': ['client:read'],
  '/[clientId]/auth': ['customer:read_profile'],
  '/:clientId/auth/register': ['customer:read_profile'],
  '/:clientId/auth/login': ['customer:read_profile'],
  '/:clientId/customer/orders': ['customer:read_profile', 'customer:read'],
  '/:clientId/admin/customers': ['customer:read_profile', 'customer:read', 'customer:delete'],
  '/backoffice/clients/:clientId/customers': ['client:read', 'customer:read', 'customer:delete'],
  '/:clientId/customer/orders/:orderId': ['customer:read_profile', 'customer:read'],
  '/[clientId]/customer/me': ['customer:read_profile'],
  '/:clientId/customer/me/profile': ['customer:read_profile'],
  '/:clientId/admin/customers/create': ['customer:read_profile', 'customer:read', 'customer:delete'],
  '/:clientId/admin/customers/:customerId': ['customer:read_profile', 'customer:read', 'customer:delete'],
  '/backoffice/clients/:clientId/customers/:customerId': ['client:read', 'customer:read', 'customer:delete', 'customer:update'],
  '/:clientId/customer/me/profile/update': ['customer:read_profile'],
  '/:clientId/admin/customers/:customerId/update': ['customer:read_profile', 'customer:read', 'customer:delete', 'customer:update'],
} as const;
